import turtle as trtl
  
painter = trtl.Turtle()

painter.penup()
painter.left(180)
painter.forward(50)
painter.right(90)
painter.forward(100)
painter.pendown()
painter.right(90)
painter.forward(75)
painter.right(90)
painter.forward(175)
painter.right(90)
painter.forward(75)
painter.right(90)
painter.forward(175)
painter.right(180)
painter.forward(140)
painter.right(20)
painter.forward(80)
painter.right(210)
painter.forward(63)
painter.right(40)
painter.forward(54)
painter.left(90)
painter.forward(35)
painter.right(160)
painter.forward(80)
painter.left(210)
painter.forward(62)
painter.left(40)
painter.forward(55)
painter.right(180)
painter.forward(37)
painter.left(90)
painter.pensize(2)
painter.forward(35)
painter.right(180)
painter.forward(80)
painter.pensize(1)
painter.right(180)
painter.forward(45)
painter.left(90)
painter.forward(37)
painter.right(90)
painter.forward(175)
painter.right(35)
painter.forward(65)
painter.right(180)
painter.forward(65)
painter.left(125)
painter.forward(75)
painter.left(125)
painter.forward(65)
painter.penup()
painter.forward(70)
painter.right(120)
painter.forward(200)
painter.pendown()
painter.circle(25)
painter.penup()
painter.left(50)
painter.forward(15)
painter.pendown()
painter.circle(5)
painter.penup()
painter.left(120)
painter.forward(170)












window = trtl.Screen()
window.mainloop()
  
